name: 'Lumadata github actions'
description: 'YAML to Lumadata'
inputs:
  repository-key:
    description: 'REPOSITORY_KEY'
    required: true
#    default: ''
  repository-secret-key:
    description: 'REPOSITORY_SECRET_KEY'
    required: true
  path-to-directory:
    description: 'Path to directory of yaml files'
    required: true
runs:
  using: 'docker'
  image: docker://lumadata/actions:0.1.0
  env:
    REPOSITORY_KEY: ${{ inputs.repository-key }}
    REPOSITORY_SECRET_KEY: ${{ inputs.repository-secret-key }}
  args:
    - yaml-to-lumadata
    - /github/workspace/${{ inputs.path-to-directory }}